export const routes = {
  auth: {
    signIn: "/auth/sign-in",
    signInStudent: "/auth/sign-in/student",
    signInManagement: "/auth/sign-in/management",
    signUp: "/auth/sign-up",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
  },
  student: {
    dashboard: "/student/dashboard",
    universities: "/student/universities",
    universityDetail: (id: string) => `/student/universities/${id}`,
    applications: "/student/applications",
    applicationDetail: (universityId: string, cycle: string) => `/student/applications/${universityId}/${cycle}`,
    applicationCreate: (universityId: string) => `/student/applications/new/${universityId}`,
    compare: "/student/compare",
    settings: "/student/settings",
    help: "/student/help",
    billing: "/student/billing",
    pricing: "/student/pricing",
    checkout: "/student/checkout",
  },
  management: {
    university: {
      dashboard: (universityId: string) => `/management/${universityId}/dashboard`,
      profile: (universityId: string) => `/management/${universityId}/profile`,
      applicationStructure: (universityId: string) => `/management/${universityId}/application-structure`,
      applications: (universityId: string) => `/management/${universityId}/applications`,
      users: (universityId: string) => `/management/${universityId}/users`,
      billing: (universityId: string) => `/management/${universityId}/billing`,
    },
    global: {
      overview: "/management/global/overview",
      universities: "/management/global/universities",
      drafts: "/management/global/drafts",
      applications: "/management/global/applications",
      users: "/management/global/users",
      serviceLogs: "/management/global/service-logs",
      auditLogs: "/management/global/audit-logs",
      settings: "/management/global/settings",
    },
    // Legacy alias for components/tests that still use superuser naming.
    superuser: {
      overview: "/management/global/overview",
      universities: "/management/global/universities",
      drafts: "/management/global/drafts",
      applications: "/management/global/applications",
      users: "/management/global/users",
      serviceLogs: "/management/global/service-logs",
      auditLogs: "/management/global/audit-logs",
      settings: "/management/global/settings",
    },
  },
} as const;

export const legacyRedirects: Record<string, string> = {
  "/": routes.auth.signIn,
  "/signin": routes.auth.signIn,
  "/signup": routes.auth.signUp,
  "/dashboard": routes.student.dashboard,
  "/search": routes.student.universities,
  "/applications": routes.student.applications,
  "/superuser/overview": routes.management.global.overview,
  "/superuser/universities": routes.management.global.universities,
  "/superuser/drafts": routes.management.global.drafts,
  "/superuser/applications": routes.management.global.applications,
  "/superuser/users": routes.management.global.users,
  "/superuser/service-logs": routes.management.global.serviceLogs,
  "/superuser/audit-logs": routes.management.global.auditLogs,
  "/superuser/settings": routes.management.global.settings,
};
