openapi: 3.0.3
info:
  title: Kallisto Backend API
  version: 1.0.0
  description: OpenAPI 3.0 documentation

  /v1.0/signup:
    post:
      tags: [ Client ]
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ email, password, fullName ]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                fullName:
                  type: string
      responses:
        '201':
          description: User registered
