openapi: 3.0.3
info:
  title: Kallisto Backend API
  version: 1.0.0
  description: OpenAPI 3.0 documentation


  /v1.0/universities:
    get:
      tags: [ Client ]
      summary: List universities
      responses:
        '200':
          description: University list

    /v1.0/universities/{university_uid}:
      get:
        tags: [ Client ]
        summary: Get university info
        parameters:
          - name: university_uid
            in: path
            required: true
            schema:
              type: string

    /v1.0/universities/{university_uid}/add:
      post:
        tags: [ Client ]
        summary: Add university to list
        parameters:
          - name: university_uid
            in: path
            required: true
            schema:
              type: string
