openapi: 3.0.3
info:
  title: Kallisto Backend API
  version: 1.0.0
  description: OpenAPI 3.0 documentation


paths:
  /v1.0/drafts:
    get:
      tags: [ Admin ]
      summary: List drafts
      responses:
        '200':
          description: Drafts list

    /v1.0/drafts/approve:
      post:
        tags: [ Admin ]
        summary: Approve draft
        responses:
          '200':
            description: Approved

    /v1.0/drafts/disapprove:
      post:
        tags: [ Admin ]
        summary: Disapprove draft
        responses:
          '200':
            description: Disapproved

    /v1.0/drafts/{draft_id}:
      delete:
        tags: [ Admin ]
        summary: Delete draft
        parameters:
          - name: draft_id
            in: path
            required: true
            schema:
              type: string
        responses:
          '204':
            description: Deleted
