openapi: 3.0.3
info:
  title: Kallisto Backend API
  version: 1.0.0
  description: OpenAPI 3.0 documentation

paths:
  /v1.0/generate-account:
    post:
      tags: [ Admin ]
      summary: Generate applicant account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Account generated
