openapi: 3.0.3
info:
  title: Kallisto Backend API
  version: 1.0.0
  description: OpenAPI 3.0 documentation

paths:
  /v1.0/login:
    post:
      tags: [Client, Admin]
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Auth tokens

  /v1.0/logout:
    post:
      tags: [Client, Admin]
      summary: Logout user
      responses:
        '200':
          description: Logged out
